spring:
  application:
    name: books
  datasource:
    url: jdbc:postgresql://localhost:5432/books
    username: postgres
    password: postgres123
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
server:
  port: 8080
  address: 127.0.0.1
